# SonarQube configuration
sonar.projectKey=prueba-estatica
sonar.projectName=prueba estatica
sonar.sourceEncoding=UTF-8

# Paths
sonar.sources=.

# Excludes
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, **/build/**, **/public/**, **/*.test.js, **/*.spec.js

# SonarQube server
sonar.host.url=http://localhost:9000
